name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install libusb-1.0-0-dev libexif-dev

    - name: Build
      run: cmake -B build -G Ninja && cmake --build build

    - name: Compile and run regression test
      run: |
        cmake -G Ninja -B build_test -DPTP_INCLUDE_VCAM_TEST=ON -DPTP_INCLUDE_LIBUSB_LIBS=OFF
        cmake --build build_test
        build_test/test

  macOS-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install libusb --force

    - name: Build
      run: cmake -B build -G Ninja && cmake --build build
